Update buildapp.yml

diff --git a/.github/workflows/buildapp.yml b/.github/workflows/buildapp.yml
--- a/.github/workflows/buildapp.yml
+++ b/.github/workflows/buildapp.yml
@@ -137,6 +137,23 @@ jobs:
           THEOS: ${{ github.workspace }}/theos
           YOUTUBE_URL: ${{ env.URL_YT }}
 
+      - name: Fix delhiIconsEnabled Compilation Error
+        run: |
+          cd ${{ github.workspace }}/main
+          
+          # Fix the compilation error in Tweak.x
+          if [ -f "Tweaks/YouPiP/Tweak.x" ]; then
+            # Add objc/message.h import if not present
+            if ! grep -q "#import <objc/message.h>" Tweaks/YouPiP/Tweak.x; then
+              echo '#import <objc/message.h>' | cat - Tweaks/YouPiP/Tweak.x > temp && mv temp Tweaks/YouPiP/Tweak.x
+            fi
+            
+            # Replace the problematic line with objc_msgSend version
+            sed -i '' 's/\[YTUIResourcesClass delhiIconsEnabled\]/((BOOL (*)(id, SEL))objc_msgSend)(YTUIResourcesClass, @selector(delhiIconsEnabled))/g' Tweaks/YouPiP/Tweak.x
+            
+            echo "==> Fixed delhiIconsEnabled compilation error"
+          fi
+
       - name: Fix compiling & Build Package
         id: build_package
         run: |
@@ -148,7 +165,6 @@ jobs:
           echo "package=$(ls -t packages | head -n1)" >>$GITHUB_OUTPUT
           echo -e "==> \033[1mSHASUM256: $(shasum -a 256 packages/*.ipa | cut -f1 -d' ')\033[0m"
           echo -e "==> \033[1mBundle ID: ${{ env.BUNDLE_ID }}\033[0m"
-
         env:
           THEOS: ${{ github.workspace }}/theos
           UYOU_VERSION: ${{ inputs.uyou_version }}
